sudo: required 

services:
  - docker

before_install:
  - docker build -t mityab/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run mityab/react-test npm test -- --coverage
after_success:
  - docker build -t mityab/multi-client ./client
  - docker build -t mityab/multi-nginx ./nginx
  - docker build -t mityab/multi-server ./server
  - docker build -t mityab/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push mityab/multi-client
  - docker push mityab/multi-nginx
  - docker push mityab/multi-server
  - docker push mityab/multi-worker
deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-1-769887816446
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
